---
title: "p8105_hw6_xl3494"
author: Selina Lyu
output: github_document
---
```{r, include = FALSE}
library(tidyverse)
library(broom)

set.seed(1)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Import the raw data
```{r}
hom_raw = readr::read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

Clean the dataset

```{r}
hom = 
  hom_raw |>
  mutate(city_state = str_c(city,", ", state),
         solved = disposition == "Closed by arrest",
         victim_age = as.numeric(victim_age)) |>
  mutate(solved = as.integer(solved)) |>
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ",
                       "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black"),
    !is.na(victim_age)
  )
```









